"""
Django settings for portal_libros_seguro_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os # Asegúrate de que esta línea esté al principio del archivo
#from decouple import config # Necesitarás instalar django-decouple para esto

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$8!c57=0wfg)x-lf-razz%b3lwmbf%fc5x!9ln4mjd*a2h2mi9'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.getenv("DEBUG","False") == "TRUE"

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'libros',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portal_libros_seguro_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Esto busca plantillas en una carpeta 'templates' en la raíz del proyecto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug', #este es nuevo
            ],
        },
    },
]

WSGI_APPLICATION = 'portal_libros_seguro_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("DATABASE_URL")
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Configuración de seguridad para producción
#DEBUG = config('DEBUG', default=False, cast=bool) # Establece DEBUG en False en producción
#ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1').split(',') # Permite acceso solo desde estos hosts/dominios
#SECRET_KEY = config('SECRET_KEY') # Obtén la SECRET_KEY de una variable de entorno


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #nuevo tambiem
# Configuración para archivos MEDIA (archivos subidos por los usuarios, como portadas y PDFs)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles') # Carpeta donde se guardarán los archivos subidos (libros, portadas)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# URL a la que redirigir después de un inicio de sesión exitoso
LOGIN_REDIRECT_URL = '/' # Redirige a la página principal después de login

# URL a la que redirigir después de un cierre de sesión exitoso
LOGOUT_REDIRECT_URL = '/' # Redirige a la página principal después de logout

# URL de la página de inicio de sesión.
# Django espera una plantilla en 'registration/login.html' para la vista de login por defecto.
LOGIN_URL = '/accounts/login/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1, # Versión del esquema de configuración de logging
    'disable_existing_loggers': False, # No deshabilitar loggers existentes
    'formatters': { # Define formatos de los mensajes de log
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': { # Define dónde se enviarán los mensajes de log
        'console': { # Envía logs a la consola (CMD)
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': { # Envía logs a un archivo
            'level': 'INFO', # Nivel mínimo de log a guardar en el archivo
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_audit.log'), # El archivo se creará en la raíz del proyecto
            'formatter': 'verbose'
        },
    },
    'loggers': { # Define qué loggers existen y qué handlers usarán
        'django': { # Logger para Django
            'handlers': ['console', 'file'],
            'level': 'INFO', # Nivel mínimo para logs de Django
            'propagate': False, # No propagar logs a loggers padre
        },
        'libros': { # Logger específico para tu aplicación 'libros'
            'handlers': ['console', 'file'],
            'level': 'INFO', # Nivel mínimo para logs de tu app
            'propagate': False,
        },
    },
}